# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    env:
      DIRECTORY: 'Android-Legacy'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get Dependency dlls
      uses: actions/checkout@v4
      with:
        repository: Vanilla-Expanded/VanillaExpandedFramework
        path: Source/libs/VanillaExpandedFramework
    - name: Get Dependency dlls
      uses: actions/checkout@v4
      with:
        repository: Vanilla-Expanded/VanillaPsycastsExpanded
        path: Source/libs/VanillaPsycastsExpanded
    - name: Get Dependency dlls
      uses: actions/checkout@v4
      with:
        repository: erdelf/AlienRaces
        path: Source/libs/AlienRaces
    - name: Copy Dependency dlls
      shell: bash
      #cp -n prevents it from overwriting existing files
      # tag format must be v${version}.X.Y(-(alpha|RC|beta))
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        RW_VERSION=${TAG_NAME:1:3}
        find  Source/libs/VanillaExpandedFramework/$RW_VERSION/Assemblies \
              Source/libs/VanillaPsycastsExpanded/$RW_VERSION/Assemblies \
              Source/libs/AlienRaces/$RW_VERSION/Assemblies -type f -exec cp -n {} Source/libs \;
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Compile
      shell: bash
      run: |
          dotnet build Source/Androids.sln -p:Configuration=release -p:ReferencePath=libs
    - name: zip release
      uses: TheDoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'Androids-HSK${{github.ref_name}}.zip'
        exclusions: '.git Source .gitattributes .gitignore .github libs'
    - name: check files
      run: ls
    - name: Release
      uses: softprops/action-gh-release@v0.1.13
      with:
        tag_name: ${{ github.ref_name }}
        name: Androids ${{ github.ref_name }}
        body: built with Github Actions
        draft: false
        prerelease: ${{ contains(github.ref_name, 'RC') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') }}
        files: |
          Androids-HSK${{github.ref_name}}.zip